[project]
name = "sdl"
version = "1.3.1"
description = "SDL bindings for Mire (SDL2 + SDL3)"
entry = "code/mod.mire"

[build]
compiler = "mire"
profile = "debug"
opt-level = 0
artifact = "shared"
runtime = "full"
target = "x86_64-unknown-linux-gnu"
panic = "abort"
incremental = true
debug-info = true

[paths]
sources = "code"
tests = "tests"
output = "bin"
cache = "bin/.cache"
source = "code"
test = "tests"
bin = "bin"
generated = "bin/generated"

[cfg]
publisher = "publish.toml"
registry = "mor"

[dependencies]
mire = { path = "~/.owl/libs/mire" }
kioto = { path = "~/.owl/libs/kioto" }
sdl = { path = "." }

[exports]
sdl3 = "code/sdl3"
sdl2 = "code/sdl2"
["owl@lock"]
version = "3"
